package HealthBuddy.ui.donor;

import javax.swing.*;

import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Role.Donor;
import HealthBuddy.models.UserData.DonorData;
import HealthBuddy.Config.Config;
import HealthBuddy.models.DB4OUtil.DB4OUtil;
import javax.swing.ImageIcon;
import java.awt.Image;


/**
 *
 * @author Nidhi Singh
 */
public class DonorValidateJPanel extends javax.swing.JPanel {
    private DonorData donorData;
    private JPanel bodyPanel;
    private EcoSystem ecosystem;
    private boolean isValidated;
    private String validationCode;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form ValidateDonorJPanel
     */
    public DonorValidateJPanel(JPanel bodyPanel, EcoSystem ecosystem, String code, DonorData donorData) {
        initComponents();
        this.bodyPanel = bodyPanel;
        this.ecosystem = ecosystem;
        validationCode = code;
        this.donorData = donorData;
        setValidated(false);
        setSize(1540,800);
    }
    
    public boolean getValidated() {
        return isValidated;
    }
    
    public void setValidated(boolean valid) {
       isValidated = valid;
       
       if (isValidated) {
           valAccL.setVisible(false);
           codeL.setVisible(false);
           codeTF.setVisible(false);
           helperLabel.setVisible(false);
           registerBtn.setVisible(false);

           setAccL.setVisible(true);
           userNameLabel.setVisible(true);
           usernameTF.setVisible(true);
           passPF.setVisible(true);
           paswdL.setVisible(true);
           saveBtn.setVisible(true);
       
       } else {

           valAccL.setVisible(true);
           codeL.setVisible(true);
           codeTF.setVisible(true);
           helperLabel.setVisible(true);
           registerBtn.setVisible(true);


           setAccL.setVisible(false);
           userNameLabel.setVisible(false);
           usernameTF.setVisible(false);
           passPF.setVisible(false);
           paswdL.setVisible(false);
           saveBtn.setVisible(false);
       
       }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAccL = new javax.swing.JLabel();
        codeL = new javax.swing.JLabel();
        codeTF = new javax.swing.JTextField();
        helperLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        valAccL = new javax.swing.JLabel();
        paswdL = new javax.swing.JLabel();
        passPF = new javax.swing.JPasswordField();
        saveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        setAccL.setBackground(new java.awt.Color(255, 255, 255));
        setAccL.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        setAccL.setForeground(new java.awt.Color(0, 102, 102));
        setAccL.setText("SET YOUR ACCOUNT AS A DONOR");

        codeL.setBackground(new java.awt.Color(255, 255, 255));
        codeL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codeL.setForeground(new java.awt.Color(0, 102, 102));
        codeL.setText("Code: ");

        codeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codeTF.setForeground(new java.awt.Color(0, 102, 102));
        codeTF.setText(" ");

        helperLabel.setBackground(new java.awt.Color(255, 255, 255));
        helperLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helperLabel.setForeground(new java.awt.Color(0, 102, 102));
        helperLabel.setText("Please check your email you will have received a code. Please check the spam folder as well.");

        registerBtn.setBackground(new java.awt.Color(0, 102, 102));
        registerBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Validate");
        registerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerBtn.setBorderPainted(false);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        userNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 102, 102));
        userNameLabel.setText("Username:");

        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(0, 102, 102));
        usernameTF.setText(" ");

        valAccL.setBackground(new java.awt.Color(255, 255, 255));
        valAccL.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        valAccL.setForeground(new java.awt.Color(0, 102, 102));
        valAccL.setText("VALIDATE YOUR ACCOUNT AS A DONOR");

        paswdL.setBackground(new java.awt.Color(255, 255, 255));
        paswdL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paswdL.setForeground(new java.awt.Color(0, 102, 102));
        paswdL.setText("Password:");

        passPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passPF.setForeground(new java.awt.Color(0, 102, 102));
        passPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPFActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 102, 102));
        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBtn.setBorderPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/accvalidate.gif")).getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codeL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(setAccL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(123, 123, 123)
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paswdL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(875, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(valAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1646, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeL)
                    .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helperLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerBtn)
                            .addComponent(setAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paswdL)
                            .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(saveBtn))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(valAccL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(865, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        
        boolean valid = Config.getClippedText(codeTF).equals(validationCode);
        setValidated(valid);

    }//GEN-LAST:event_registerBtnActionPerformed

    private void passPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPFActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        String userName = Config.getClippedText(usernameTF);
        String password = String.valueOf(passPF.getPassword());
        
        boolean result = ecosystem.getUserCatalog().isUserNameUnique(userName);
        
        if (result) {
            donorData.setUsername(userName);
            ecosystem.getUserCatalog().newDonorAccount(userName, password, donorData, new Donor());
            ecosystem.getDonorDir().addDonor(donorData);
            dB4OUtil.storeSystem(ecosystem);

            JOptionPane.showMessageDialog(null, "You have been officially registered as Donor \nPlease Login to start donating.. ",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
            saveBtn.setEnabled(false);
            usernameTF.setEditable(false);
            passPF.setEditable(false);
            usernameTF.setText("");
            passPF.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Try a different username, current username already exists","Error", JOptionPane.ERROR_MESSAGE);
            usernameTF.setText("");
            passPF.setText("");
        }
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeL;
    private javax.swing.JTextField codeTF;
    private javax.swing.JLabel helperLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passPF;
    private javax.swing.JLabel paswdL;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel setAccL;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JLabel valAccL;
    // End of variables declaration//GEN-END:variables
}
