package HealthBuddy.ui.donor;

import javax.swing.*;

import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Role.Donor;
import HealthBuddy.models.UserData.DonorData;
import HealthBuddy.Config.Config;
import HealthBuddy.models.DB4OUtil.DB4OUtil;
import javax.swing.ImageIcon;
import java.awt.Image;


/**
 *
 * @author Nidhi Singh
 */
public class DonorValidateJPanel extends javax.swing.JPanel {
    private DonorData donorData;
    private JPanel bodyPanel;
    private EcoSystem ecosystem;
    private boolean isValidated;
    private String validationCode;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form ValidateDonorJPanel
     */
    public DonorValidateJPanel(JPanel bodyPanel, EcoSystem ecosystem, String code, DonorData donorData) {
        initComponents();
        this.bodyPanel = bodyPanel;
        this.ecosystem = ecosystem;
        validationCode = code;
        this.donorData = donorData;
        setValidated(false);
        setSize(1540,800);
    }
    
    public boolean getValidated() {
        return isValidated;
    }
    
    public void setValidated(boolean valid) {
       isValidated = valid;
       
       if (isValidated) {
           valAccL9.setVisible(false);
           codeL9.setVisible(false);
           codeTF9.setVisible(false);
           helperLabel9.setVisible(false);
           registerBtn9.setVisible(false);

           setAccL9.setVisible(true);
           userNameLabel9.setVisible(true);
           usernameTF9.setVisible(true);
           passPF9.setVisible(true);
           paswdL9.setVisible(true);
           saveBtn9.setVisible(true);
       
       } else {

           valAccL9.setVisible(true);
           codeL9.setVisible(true);
           codeTF9.setVisible(true);
           helperLabel9.setVisible(true);
           registerBtn9.setVisible(true);


           setAccL9.setVisible(false);
           userNameLabel9.setVisible(false);
           usernameTF9.setVisible(false);
           passPF9.setVisible(false);
           paswdL9.setVisible(false);
           saveBtn9.setVisible(false);
       
       }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAccL9 = new javax.swing.JLabel();
        codeL9 = new javax.swing.JLabel();
        codeTF9 = new javax.swing.JTextField();
        helperLabel9 = new javax.swing.JLabel();
        registerBtn9 = new javax.swing.JButton();
        userNameLabel9 = new javax.swing.JLabel();
        usernameTF9 = new javax.swing.JTextField();
        valAccL9 = new javax.swing.JLabel();
        paswdL9 = new javax.swing.JLabel();
        passPF9 = new javax.swing.JPasswordField();
        saveBtn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        setAccL9.setBackground(new java.awt.Color(255, 255, 255));
        setAccL9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        setAccL9.setForeground(new java.awt.Color(0, 102, 102));
        setAccL9.setText("SET YOUR ACCOUNT AS A DONOR");

        codeL9.setBackground(new java.awt.Color(255, 255, 255));
        codeL9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codeL9.setForeground(new java.awt.Color(0, 102, 102));
        codeL9.setText("Code: ");

        codeTF9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codeTF9.setForeground(new java.awt.Color(0, 102, 102));
        codeTF9.setText(" ");

        helperLabel9.setBackground(new java.awt.Color(255, 255, 255));
        helperLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helperLabel9.setForeground(new java.awt.Color(0, 102, 102));
        helperLabel9.setText("Please check your email you will have received a code. Please check the spam folder as well.");

        registerBtn9.setBackground(new java.awt.Color(0, 102, 102));
        registerBtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registerBtn9.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn9.setText("Validate");
        registerBtn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerBtn9.setBorderPainted(false);
        registerBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtn9ActionPerformed(evt);
            }
        });

        userNameLabel9.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameLabel9.setForeground(new java.awt.Color(0, 102, 102));
        userNameLabel9.setText("Username:");

        usernameTF9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameTF9.setForeground(new java.awt.Color(0, 102, 102));
        usernameTF9.setText(" ");

        valAccL9.setBackground(new java.awt.Color(255, 255, 255));
        valAccL9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        valAccL9.setForeground(new java.awt.Color(0, 102, 102));
        valAccL9.setText("VALIDATE YOUR ACCOUNT AS A DONOR");

        paswdL9.setBackground(new java.awt.Color(255, 255, 255));
        paswdL9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paswdL9.setForeground(new java.awt.Color(0, 102, 102));
        paswdL9.setText("Password:");

        passPF9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passPF9.setForeground(new java.awt.Color(0, 102, 102));
        passPF9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPF9ActionPerformed(evt);
            }
        });

        saveBtn9.setBackground(new java.awt.Color(0, 102, 102));
        saveBtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveBtn9.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn9.setText("Save");
        saveBtn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBtn9.setBorderPainted(false);
        saveBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn9ActionPerformed(evt);
            }
        });

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/accvalidate.gif")).getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codeL9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeTF9, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helperLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(setAccL9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(usernameTF9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(123, 123, 123)
                                .addComponent(registerBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paswdL9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passPF9, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(875, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(valAccL9, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1646, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeL9)
                    .addComponent(codeTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helperLabel9)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerBtn9)
                            .addComponent(setAccL9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel9)
                            .addComponent(usernameTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paswdL9)
                            .addComponent(passPF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(saveBtn9))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(valAccL9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(865, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtn9ActionPerformed
        // TODO add your handling code here:
        
        boolean valid = Config.getClippedText(codeTF9).equals(validationCode);
        setValidated(valid);

    }//GEN-LAST:event_registerBtn9ActionPerformed

    private void passPF9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPF9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPF9ActionPerformed

    private void saveBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn9ActionPerformed
        // TODO add your handling code here:
        
        String userName = Config.getClippedText(usernameTF9);
        String password = String.valueOf(passPF9.getPassword());
        
        boolean result = ecosystem.getUserCatalog().isUserNameUnique(userName);
        
        if (result) {
            donorData.setUsername(userName);
            ecosystem.getUserCatalog().newDonorAccount(userName, password, donorData, new Donor());
            ecosystem.getDonorDir().addDonor(donorData);
            dB4OUtil.storeSystem(ecosystem);

            JOptionPane.showMessageDialog(null, "Your Donor registration is complete \nPlease Signin to begin your contribution",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
            saveBtn9.setEnabled(false);
            usernameTF9.setEditable(false);
            passPF9.setEditable(false);
            usernameTF9.setText("");
            passPF9.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Please try with a unique username, this username is already used","Error", JOptionPane.ERROR_MESSAGE);
            usernameTF9.setText("");
            passPF9.setText("");
        }
    }//GEN-LAST:event_saveBtn9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeL9;
    private javax.swing.JTextField codeTF9;
    private javax.swing.JLabel helperLabel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passPF9;
    private javax.swing.JLabel paswdL9;
    private javax.swing.JButton registerBtn9;
    private javax.swing.JButton saveBtn9;
    private javax.swing.JLabel setAccL9;
    private javax.swing.JLabel userNameLabel9;
    private javax.swing.JTextField usernameTF9;
    private javax.swing.JLabel valAccL9;
    // End of variables declaration//GEN-END:variables
}
