package HealthBuddy.ui.patient;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.DB4OUtil.DB4OUtil;
import HealthBuddy.models.Role.Patient;
import HealthBuddy.models.Role.Donor;
import HealthBuddy.models.UserData.PatientData;
import HealthBuddy.models.UserData.DonorData;
import HealthBuddy.Config.Config;
import HealthBuddy.ui.donor.*;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Dimple Patel
 */
public class PatientValidateJPanel extends javax.swing.JPanel {
     private PatientData patientData;
    private JPanel bodyPanel;
    private EcoSystem ecosystem;
    private boolean isValidated;
    private String validationCode;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form ValidateDonorJPanel
     */
    public PatientValidateJPanel(JPanel bodyPanel, EcoSystem ecosystem, String code, PatientData patient) {
        initComponents();
         this.bodyPanel = bodyPanel;
        this.ecosystem = ecosystem;
        validationCode = code;
        this.patientData = patient;
        setValidated(false);
        setSize(1540,800);
    }
    
    
    public boolean getValidated() {
        return isValidated;
    }
    
    public void setValidated(boolean valid) {
       isValidated = valid;
       
       if (isValidated) {
           verifypatacclabel.setVisible(false);
           OTPlabel.setVisible(false);
           oTPTextF.setVisible(false);
           otPlabel.setVisible(false);
           buttonverify.setVisible(false);

           accsetuplabel.setVisible(true);
           unmlabel.setVisible(true);
           unmTextF.setVisible(true);
           psswrdTextF.setVisible(true);
           psswrdlabel.setVisible(true);
           buttonsv.setVisible(true);
       
       } else {

           verifypatacclabel.setVisible(true);
           OTPlabel.setVisible(true);
           oTPTextF.setVisible(true);
           otPlabel.setVisible(true);
           buttonverify.setVisible(true);


           accsetuplabel.setVisible(false);
           unmlabel.setVisible(false);
           unmTextF.setVisible(false);
           psswrdTextF.setVisible(false);
           psswrdlabel.setVisible(false);
           buttonsv.setVisible(false);
       
       }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accsetuplabel = new javax.swing.JLabel();
        OTPlabel = new javax.swing.JLabel();
        oTPTextF = new javax.swing.JTextField();
        otPlabel = new javax.swing.JLabel();
        buttonverify = new javax.swing.JButton();
        unmlabel = new javax.swing.JLabel();
        unmTextF = new javax.swing.JTextField();
        verifypatacclabel = new javax.swing.JLabel();
        psswrdlabel = new javax.swing.JLabel();
        psswrdTextF = new javax.swing.JPasswordField();
        buttonsv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        accsetuplabel.setBackground(new java.awt.Color(255, 255, 255));
        accsetuplabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        accsetuplabel.setForeground(new java.awt.Color(0, 102, 102));
        accsetuplabel.setText("Patient Account Setup");

        OTPlabel.setBackground(new java.awt.Color(255, 255, 255));
        OTPlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OTPlabel.setForeground(new java.awt.Color(0, 102, 102));
        OTPlabel.setText("One Time Password");

        oTPTextF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oTPTextF.setForeground(new java.awt.Color(0, 102, 102));
        oTPTextF.setText(" ");

        otPlabel.setBackground(new java.awt.Color(255, 255, 255));
        otPlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otPlabel.setForeground(new java.awt.Color(0, 102, 102));
        otPlabel.setText("Kindly check your SMS inbox for one time password verification.");

        buttonverify.setBackground(new java.awt.Color(0, 102, 102));
        buttonverify.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        buttonverify.setForeground(new java.awt.Color(255, 255, 255));
        buttonverify.setText("Verify");
        buttonverify.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonverify.setBorderPainted(false);
        buttonverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonverifyActionPerformed(evt);
            }
        });

        unmlabel.setBackground(new java.awt.Color(255, 255, 255));
        unmlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        unmlabel.setForeground(new java.awt.Color(0, 102, 102));
        unmlabel.setText("Username:");

        unmTextF.setForeground(new java.awt.Color(0, 0, 102));
        unmTextF.setText(" ");

        verifypatacclabel.setBackground(new java.awt.Color(255, 255, 255));
        verifypatacclabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        verifypatacclabel.setForeground(new java.awt.Color(0, 102, 102));
        verifypatacclabel.setText("Dear Patient, Verify Your Account !");

        psswrdlabel.setBackground(new java.awt.Color(255, 255, 255));
        psswrdlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        psswrdlabel.setForeground(new java.awt.Color(0, 102, 102));
        psswrdlabel.setText("Password:");

        psswrdTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswrdTextFActionPerformed(evt);
            }
        });

        buttonsv.setBackground(new java.awt.Color(0, 102, 102));
        buttonsv.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        buttonsv.setForeground(new java.awt.Color(255, 255, 255));
        buttonsv.setText("Save");
        buttonsv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonsv.setBorderPainted(false);
        buttonsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsvActionPerformed(evt);
            }
        });

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/accvalidate.gif")).getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OTPlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oTPTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otPlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(647, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonsv, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unmlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psswrdlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(unmTextF)
                                    .addComponent(psswrdTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accsetuplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143))
                            .addComponent(buttonverify, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(verifypatacclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(694, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OTPlabel)
                    .addComponent(oTPTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otPlabel)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonverify)
                        .addGap(56, 56, 56)
                        .addComponent(accsetuplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unmlabel)
                            .addComponent(unmTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psswrdlabel)
                            .addComponent(psswrdTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(buttonsv))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(verifypatacclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(699, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonverifyActionPerformed
        // TODO add your handling code here:
        boolean valid = Config.getClippedText(oTPTextF).equals(validationCode);
        setValidated(valid);


    }//GEN-LAST:event_buttonverifyActionPerformed

    private void psswrdTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psswrdTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psswrdTextFActionPerformed

    private void buttonsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsvActionPerformed
        // TODO add your handling code here:
        
        String userName = Config.getClippedText(unmTextF);
        String password = String.valueOf(psswrdTextF.getPassword());
        
        boolean result = ecosystem.getUserCatalog().isUserNameUnique(userName);
        
        if (result) {
            patientData.setUsername(userName);
            ecosystem.getUserCatalog().newPatientAccount(userName, password,
                    patientData, new Patient());
            ecosystem.getPatientDir().addPat(patientData);
            dB4OUtil.storeSystem(ecosystem);

            JOptionPane.showMessageDialog(null, "Your Registration as Patient is Successful \nKindly Signin now to get started ",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
            buttonsv.setEnabled(false);
            unmTextF.setEditable(false);
            psswrdTextF.setEditable(false);
            unmTextF.setText("");
            psswrdTextF.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Kindly try a with different credentials, these credentials already exists","Error", JOptionPane.ERROR_MESSAGE);
            unmTextF.setText("");
            psswrdTextF.setText("");
        }
    }//GEN-LAST:event_buttonsvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OTPlabel;
    private javax.swing.JLabel accsetuplabel;
    private javax.swing.JButton buttonsv;
    private javax.swing.JButton buttonverify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField oTPTextF;
    private javax.swing.JLabel otPlabel;
    private javax.swing.JPasswordField psswrdTextF;
    private javax.swing.JLabel psswrdlabel;
    private javax.swing.JTextField unmTextF;
    private javax.swing.JLabel unmlabel;
    private javax.swing.JLabel verifypatacclabel;
    // End of variables declaration//GEN-END:variables
}
