package HealthBuddy.ui.BloodDonorCenter;

import javax.swing.ImageIcon;
import HealthBuddy.models.BloodDonorCenter.Organisation.BDCControllerOrganisation;
import HealthBuddy.models.EcoSystem;
import java.awt.Image;
import HealthBuddy.models.Enterprise.EnterpriseBloodDonorCenter;
import HealthBuddy.models.Network.Network;
import HealthBuddy.models.User.User;
import HealthBuddy.models.Healthcare.Organisation.HealthcareOrganisationAttendant;
import HealthBuddy.ui.attendant.WorkAreaAttendantJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nidhi Singh
 */
public class BloodDonorCenterControllerMainPageJPanel extends javax.swing.JPanel {

    private JPanel showPanel;
    private User userAccount;
    private BDCControllerOrganisation headsOrganisation;
    private EcoSystem ecoSystem;
    private Network network;
    private EnterpriseBloodDonorCenter enterprise;

    /**
     * Creates new form BloodBankInchargeLandingJPanel
     */
    public BloodDonorCenterControllerMainPageJPanel(JPanel showPanel, User account, BDCControllerOrganisation headsOrganisation, EnterpriseBloodDonorCenter bloodbankEnterprise, Network network, EcoSystem ecoSystem) {
        initComponents();
        this.showPanel = showPanel;
        setSize(1540, 800);
        this.headsOrganisation = headsOrganisation;
        this.userAccount = account;
        this.enterprise = bloodbankEnterprise;
        this.ecoSystem = ecoSystem;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewRequestjButton9 = new javax.swing.JButton();
        GoToInventoryjButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("BBI Landing Area"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewRequestjButton9.setBackground(new java.awt.Color(0, 102, 102));
        ViewRequestjButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewRequestjButton9.setForeground(new java.awt.Color(255, 255, 255));
        ViewRequestjButton9.setText("View Requests");
        ViewRequestjButton9.setBorderPainted(false);
        ViewRequestjButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRequestjButton9ActionPerformed(evt);
            }
        });
        add(ViewRequestjButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, 66));

        GoToInventoryjButton9.setBackground(new java.awt.Color(0, 102, 102));
        GoToInventoryjButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GoToInventoryjButton9.setForeground(new java.awt.Color(255, 255, 255));
        GoToInventoryjButton9.setText("Go To Inventory");
        GoToInventoryjButton9.setBorderPainted(false);
        GoToInventoryjButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToInventoryjButton9ActionPerformed(evt);
            }
        });
        add(GoToInventoryjButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 220, 66));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Blood Donor Center Controller");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        ImageIcon imageIcon =  new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/bdc.jpg")).getImage().getScaledInstance(1100, 700, Image.SCALE_DEFAULT));
        jLabel2.setIcon(imageIcon);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 1090, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewRequestjButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRequestjButton9ActionPerformed

        BloodDonorCenterControllerWorkAreaJPanel headBloodBankWorkAreaPanel = new BloodDonorCenterControllerWorkAreaJPanel(showPanel, userAccount, headsOrganisation, enterprise, network, ecoSystem);
        showPanel.add("HeadBloodBankWorkAreaJPanel", headBloodBankWorkAreaPanel);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.next(showPanel);


    }//GEN-LAST:event_ViewRequestjButton9ActionPerformed

    private void GoToInventoryjButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToInventoryjButton9ActionPerformed
        // TODO add your handling code here:
        BloodDonorCenterStorageJPanel bloodBankStoragePanel = new BloodDonorCenterStorageJPanel(showPanel, userAccount, headsOrganisation, enterprise, network, ecoSystem);
        showPanel.add("BloodBankStorageJPanel", bloodBankStoragePanel);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.next(showPanel);


    }//GEN-LAST:event_GoToInventoryjButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToInventoryjButton9;
    private javax.swing.JButton ViewRequestjButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
