package HealthBuddy.ui.BloodDonorCenter;

import HealthBuddy.models.BloodDonorCenter.Inventory.BloodDonorCenterInventoryCatalog;
import HealthBuddy.models.BloodDonorCenter.Organisation.BDCControllerOrganisation;
import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Enterprise.EnterpriseBloodDonorCenter;
import HealthBuddy.models.Enterprise.Enterprise;
import HealthBuddy.models.Network.Network;
import HealthBuddy.models.Organisation.Organisation;
import HealthBuddy.models.User.User;
import HealthBuddy.models.WorkQueue.BloodControllerAttendantWQ;
import HealthBuddy.models.WorkQueue.WorkRequest;
import HealthBuddy.models.Healthcare.Organisation.HealthcareOrganisationAttendant;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nidhi Singh
 */
public class BloodDonorCenterControllerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodDonorCenterControllerWorkAreaJPanel
     */
   
    private JPanel showPanel;
    private User userAccount;
    private BDCControllerOrganisation headsOrganisation;
    private EcoSystem system;
    private Network network;
    private EnterpriseBloodDonorCenter enterprise;
    private BloodDonorCenterInventoryCatalog bloodBankStockDirectory;

    public BloodDonorCenterControllerWorkAreaJPanel(JPanel displayJPanel, User userAccount, BDCControllerOrganisation headsOrganisation, EnterpriseBloodDonorCenter enterprise, Network network, EcoSystem business) {
               
       
        initComponents();
        this.showPanel=displayJPanel;
        this.headsOrganisation = headsOrganisation;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = business;
        this.network=network;
        this.userAccount=userAccount;
        this.bloodBankStockDirectory = this.headsOrganisation.getBbStockDirectory();    
        populateTable();
        setSize(1540,800);
    }
   
    
    
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) BloodRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request :network.getBloodDonorCenterRequests().getWorkRequestList())
        {
            BloodControllerAttendantWQ nb = (BloodControllerAttendantWQ)request;
            Object[] row = new Object[4];
            row[0] = nb;
            row[1] = nb.getTypeOfBlood();
            row[2] = nb.getUnitsOfBlood();
            row[3]=request.getMessage();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BloodRequestJTable = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Blood Requests"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BloodRequestJTable.setForeground(new java.awt.Color(0, 102, 102));
        BloodRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Blood Group", "Quantity Required", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BloodRequestJTable);
        if (BloodRequestJTable.getColumnModel().getColumnCount() > 0) {
            BloodRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            BloodRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            BloodRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            BloodRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 540, 170));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setText("Blood Request");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 260, 34));

        btnAccept.setBackground(new java.awt.Color(0, 102, 102));
        btnAccept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Accept Request");
        btnAccept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccept.setBorderPainted(false);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 190, 40));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1293, 30, 90, 40));

        ImageIcon imageIcon =  new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/bloodRequest.jpg")).getImage().getScaledInstance(950, 550, Image.SCALE_DEFAULT));
        jLabel1.setIcon(imageIcon);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 900, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
       int selectedRow=BloodRequestJTable.getSelectedRow();
       
       if(selectedRow<0)
       {
           JOptionPane.showMessageDialog(null, "No row is selected","Warning", JOptionPane.WARNING_MESSAGE);
       }
       else
       {
           BloodControllerAttendantWQ  bloodHeadAttendentWorkQueue = (BloodControllerAttendantWQ)BloodRequestJTable.getValueAt(selectedRow, 0);
           boolean result = bloodBankStockDirectory.checkBloodQuantity(bloodHeadAttendentWorkQueue.getTypeOfBlood(), bloodHeadAttendentWorkQueue.getUnitsOfBlood());
           
           if(bloodHeadAttendentWorkQueue.getMessage().equals("Blood Supplied"))
           {
               JOptionPane.showMessageDialog(null, "Blood is Delivered earlier","Warning", JOptionPane.WARNING_MESSAGE);
           }
           
           else if(result == true)
           {
                    bloodHeadAttendentWorkQueue.setMessage("Blood Supplied");
                    populateTable();
                
                    BloodControllerAttendantWQ bhawq= new BloodControllerAttendantWQ();
                             
                    bhawq.setSender(userAccount);
                    bhawq.setStatus("Blood Supplied");
                    bhawq.setTypeOfBlood(bloodHeadAttendentWorkQueue.getTypeOfBlood());
                    bhawq.setNameOfPatient(bloodHeadAttendentWorkQueue.getNameOfPatient());
                    bhawq.setUnitsOfBlood(bloodHeadAttendentWorkQueue.getUnitsOfBlood());
                
             
                    HealthcareOrganisationAttendant bb = null;
                    for(Network network : system.getNetworkList())
                    {
                        if(network.getNetworkName().equals(network.getNetworkName()))
                        {
                            for(Enterprise ent : network.getEnterpriseCatalog().getEnterpriseList())
                            {
                                for(Organisation org : ent.getOrganizationCatalog().getOrganizationList())
                                {
                                    if(org.getName().equalsIgnoreCase("Attendant Organisation"))
                                    {
                                        for(User uacnt : org.getUserCatalog().getUserCatalog())
                                        {
                                            if(uacnt.getUsername().equalsIgnoreCase(bloodHeadAttendentWorkQueue.getSender().getUsername()))
                                            {
                                                bb = (HealthcareOrganisationAttendant)org;
                                                break;
                                            }
                                        }
                                    }
                                }   
                            }
                    
                            if (bb!= null)
                            {
                                bb.getBloodHeadAttendantWQ().getWorkRequestList().add(bhawq);
                                userAccount.getWorkQueue().getWorkRequestList().add(bhawq);
                            }   
                
                            JOptionPane.showMessageDialog(null, "Posted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        }      
                    }
                }
           
           else
           {
               JOptionPane.showMessageDialog(null, "Sufficient blood quantity not available at present for this blood group", "Warning", JOptionPane.WARNING_MESSAGE);
           }
        } 
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        showPanel.remove(this);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BloodRequestJTable;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    
}
