package HealthBuddy.ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import HealthBuddy.ui.patient.PatientCreateJPanel;
import java.awt.Image;
import HealthBuddy.models.DB4OUtil.DB4OUtil;
import HealthBuddy.ui.signin.SigninJPanel;
import HealthBuddy.models.EcoSystem;
import HealthBuddy.ui.donor.CreateDonorJPanel;
import HealthBuddy.ui.signin.SignoutJPanel;
import HealthBuddy.Config.Config;


/**
 *
 * @author Nidhi Singh
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public MainJFrame() {

        initComponents();
        system=dB4OUtil.retrieveSystem();
        setSize(1540,830);
        setTitle("HealthBuddy System");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        headerPanel = new javax.swing.JPanel();
        LabelHealthBuddy = new javax.swing.JLabel();
        ButtonDonor = new javax.swing.JButton();
        ButtonPatient = new javax.swing.JButton();
        ButtonSI = new javax.swing.JButton();
        ButtonSO = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        mainSplitPane.setBackground(new java.awt.Color(255, 255, 255));
        mainSplitPane.setDividerSize(1);
        mainSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));

        LabelHealthBuddy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelHealthBuddy.setForeground(new java.awt.Color(255, 255, 255));
        LabelHealthBuddy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHealthBuddy.setText("HEALTH BUDDY");

        ButtonDonor.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDonor.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ButtonDonor.setForeground(new java.awt.Color(0, 102, 102));
        ButtonDonor.setText("Donor");
        ButtonDonor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDonor.setBorderPainted(false);
        ButtonDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDonorActionPerformed(evt);
            }
        });

        ButtonPatient.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPatient.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ButtonPatient.setForeground(new java.awt.Color(0, 102, 102));
        ButtonPatient.setText("Patient");
        ButtonPatient.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPatient.setBorderPainted(false);
        ButtonPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPatientActionPerformed(evt);
            }
        });

        ButtonSI.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSI.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ButtonSI.setForeground(new java.awt.Color(0, 102, 102));
        ButtonSI.setText("SignIn");
        ButtonSI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSI.setBorderPainted(false);
        ButtonSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSIActionPerformed(evt);
            }
        });

        ButtonSO.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSO.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ButtonSO.setForeground(new java.awt.Color(0, 102, 102));
        ButtonSO.setText("Sign Out");
        ButtonSO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSO.setBorderPainted(false);
        ButtonSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(649, Short.MAX_VALUE)
                .addComponent(LabelHealthBuddy, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305)
                .addComponent(ButtonSI, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonDonor)
                .addGap(18, 18, 18)
                .addComponent(ButtonPatient)
                .addGap(21, 21, 21))
        );

        headerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonDonor, ButtonPatient, ButtonSI, ButtonSO});

        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHealthBuddy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDonor)
                    .addComponent(ButtonPatient)
                    .addComponent(ButtonSI)
                    .addComponent(ButtonSO))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonDonor, ButtonPatient, ButtonSI, ButtonSO});

        mainSplitPane.setTopComponent(headerPanel);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setPreferredSize(new java.awt.Dimension(2000, 700));
        bodyPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1692, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        ImageIcon imageIcon =  new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/welcome-15.gif")).getImage().getScaledInstance(1540, 750, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);

        bodyPanel.add(jPanel1, "card2");

        mainSplitPane.setRightComponent(bodyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSIActionPerformed
        // TODO add your handling code here:
        SigninJPanel signinJPanel = new SigninJPanel(bodyPanel, system);
        bodyPanel.add("SigninJPanel", signinJPanel);
        CardLayout layout = (CardLayout) bodyPanel.getLayout();
        layout.next(bodyPanel);
        ButtonSO.setEnabled(true);
    }//GEN-LAST:event_ButtonSIActionPerformed

    private void ButtonDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDonorActionPerformed
        // TODO add your handling code here:
        CreateDonorJPanel createDonor = new CreateDonorJPanel(bodyPanel, system);
        bodyPanel.add("CreateDonorJPanel", createDonor);
        CardLayout layout = (CardLayout) bodyPanel.getLayout();
        layout.next(bodyPanel);
    }//GEN-LAST:event_ButtonDonorActionPerformed

    private void ButtonSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSOActionPerformed
        // TODO add your handling code here:
        ButtonSO.setEnabled(false);
        ButtonSI.setEnabled(true);
        ButtonDonor.setEnabled(true);
        ButtonPatient.setEnabled(true);
        
        bodyPanel.removeAll();
        SignoutJPanel signoutPanel = new SignoutJPanel(bodyPanel);
        bodyPanel.add("SignoutJPanel", signoutPanel);
        CardLayout crdLyt = (CardLayout) bodyPanel.getLayout();
        crdLyt.next(bodyPanel);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_ButtonSOActionPerformed

    private void ButtonPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPatientActionPerformed
        // TODO add your handling code here:      
        
        PatientCreateJPanel createDonor = new PatientCreateJPanel(bodyPanel, system);
        bodyPanel.add("CreatePatientJPanel", createDonor);
        CardLayout layout = (CardLayout) bodyPanel.getLayout();
        layout.next(bodyPanel);
    }//GEN-LAST:event_ButtonPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDonor;
    private javax.swing.JButton ButtonPatient;
    private javax.swing.JButton ButtonSI;
    private javax.swing.JButton ButtonSO;
    private javax.swing.JLabel LabelHealthBuddy;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane mainSplitPane;
    // End of variables declaration//GEN-END:variables
}
