package HealthBuddy.ui.SysAdminWorkArea;

import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Employee.Employee;
import HealthBuddy.models.Enterprise.Enterprise;
import HealthBuddy.models.Network.Network;
import HealthBuddy.models.Healthcare.Role.HealthcareAdmin;
import HealthBuddy.models.Trust.Role.TrustAdminRole;
import HealthBuddy.models.BloodDonorCenter.Role.BloodDonorCenterAdmin;
import HealthBuddy.models.User.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import java.awt.Image;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;


/**
 *
 * @author Dimple Patel
 */
public class AdminEnterpriseManagerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public AdminEnterpriseManagerJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateEnterpriseAdminTable();
        setSize(1540,800);
        populateNetworkComboBox();
    }

    private void populateEnterpriseAdminTable() {
        DefaultTableModel model = (DefaultTableModel) tableEnterprise.getModel();
        model.setRowCount(0);
        system.getNetworkList().forEach(net -> {
            net.getEnterpriseCatalog().getEnterpriseList().forEach(ent -> {
                ent.getUserCatalog().getUserCatalog().forEach(user -> {
                    Object[] tuple = new Object[3];
                    tuple[0] = ent.getName();
                    tuple[1] = net.getNetworkName();
                    tuple[2] = user.getUsername();
                    model.addRow(tuple);
                });

            });
        });
    }

    private void populateNetworkComboBox(){
        cmdNetwork.removeAllItems();
//        populating combobox for network
        for (int i = 0; i < system.getNetworkList().size(); i++) {
            Network network=system.getNetworkList().get(i);
            cmdNetwork.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        cmdEnterprise.removeAllItems();
//        populating combobox for enterprise
        for (int i = 0; i < network.getEnterpriseCatalog().getEnterpriseList().size(); i++) {
            Enterprise enterprise=network.getEnterpriseCatalog().getEnterpriseList().get(i);
            cmdEnterprise.addItem(enterprise);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnterprise = new javax.swing.JTable();
        networkLabel = new javax.swing.JLabel();
        cmdNetwork = new javax.swing.JComboBox();
        unameLabel = new javax.swing.JLabel();
        textuname = new javax.swing.JTextField();
        enterpriseLabel = new javax.swing.JLabel();
        cmdEnterprise = new javax.swing.JComboBox();
        buttonSubmit = new javax.swing.JButton();
        passwordLable = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nameLable = new javax.swing.JLabel();
        passText = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Enterprise Admin"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableEnterprise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableEnterprise.setForeground(new java.awt.Color(0, 102, 102));
        tableEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Location", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEnterprise.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(tableEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 530, 130));

        networkLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        networkLabel.setForeground(new java.awt.Color(0, 102, 102));
        networkLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        networkLabel.setText("Network:");
        add(networkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, 30));

        cmdNetwork.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdNetwork.setForeground(new java.awt.Color(0, 102, 102));
        cmdNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmdNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNetworkActionPerformed(evt);
            }
        });
        add(cmdNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 160, 30));

        unameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unameLabel.setForeground(new java.awt.Color(0, 102, 102));
        unameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        unameLabel.setText("Username:");
        add(unameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 80, 30));

        textuname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textuname.setForeground(new java.awt.Color(0, 102, 102));
        textuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textunameActionPerformed(evt);
            }
        });
        add(textuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 160, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Enterprise:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 100, 30));

        cmdEnterprise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdEnterprise.setForeground(new java.awt.Color(0, 102, 102));
        cmdEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmdEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 160, 30));

        buttonSubmit.setBackground(new java.awt.Color(0, 102, 102));
        buttonSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmit.setText("Submit");
        buttonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSubmit.setBorderPainted(false);
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        add(buttonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 100, 30));

        passwordLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLable.setForeground(new java.awt.Color(0, 102, 102));
        passwordLable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwordLable.setText("Password:");
        add(passwordLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 102, 102));
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 160, 30));

        nameLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLable.setForeground(new java.awt.Color(0, 102, 102));
        nameLable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLable.setText("Name:");
        add(nameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 80, 30));

        passText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(0, 102, 102));
        add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 160, 30));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, 80, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setText("Add Enterprise Admin");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 470, -1));

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/enterpriseAdmin.gif")).getImage().getScaledInstance(700, 500, Image.SCALE_DEFAULT));
        jLabel1.setIcon(imageIcon);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 800, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNetworkActionPerformed

        Network network = (Network) cmdNetwork.getSelectedItem();
        if (network != null)
            populateEnterpriseComboBox(network);
    }//GEN-LAST:event_cmdNetworkActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        
        Enterprise enterprise = (Enterprise) cmdEnterprise.getSelectedItem();
        String username = textuname.getText();
        String password = String.valueOf(passText.getPassword());
        String name = nameText.getText();
        Employee employee = enterprise.getEmployeeCatalog().addEmployee(name);
        if(enterprise.getEnterpriseClassification().equals(Enterprise.EnterpriseClassification.Trust)){
            User account = enterprise.getUserCatalog().newUserAccount(username, password, employee, new TrustAdminRole());
        }
        if(enterprise.getEnterpriseClassification().equals(Enterprise.EnterpriseClassification.Healthcare)){
            User account = enterprise.getUserCatalog().newUserAccount(username, password, employee, new HealthcareAdmin());
        }
        if(enterprise.getEnterpriseClassification().equals(Enterprise.EnterpriseClassification.BloodDonorCenter)){
            User account = enterprise.getUserCatalog().newUserAccount(username, password, employee, new BloodDonorCenterAdmin());
        }
        populateEnterpriseAdminTable();
        passText.setText("");
        textuname.setText("");
        nameText.setText("");
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminWorkAreaJPanel sysAdminwjp = (SysAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void textunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textunameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox cmdEnterprise;
    private javax.swing.JComboBox cmdNetwork;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JTable tableEnterprise;
    private javax.swing.JTextField textuname;
    private javax.swing.JLabel unameLabel;
    // End of variables declaration//GEN-END:variables
}
