package HealthBuddy.ui.SysAdminWorkArea;


import java.awt.CardLayout;
import HealthBuddy.models.Network.Network;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import HealthBuddy.models.EcoSystem;


/**
 *
 * @author Nidhi Singh
 */
public class LocationManageJPanel extends javax.swing.JPanel {
JPanel showPanel;
EcoSystem ecosystem;
    /**
     * Creates new form ManageLocationJPanel
     */
    public LocationManageJPanel(JPanel showPanel, EcoSystem ecosystem) {
        initComponents();
        this.showPanel=showPanel;
        this.ecosystem=ecosystem;
        populateLocationTable();
    }

     private void populateLocationTable() {
        DefaultTableModel model = (DefaultTableModel) LocationJTable.getModel();
        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getNetworkName();
            model.addRow(row);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LocationJTable = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        txtEnterCity = new javax.swing.JTextField();
        addCityjLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Network"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LocationJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LocationJTable.setForeground(new java.awt.Color(0, 102, 102));
        LocationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LocationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 404, 91));

        btnSubmit.setBackground(new java.awt.Color(0, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorderPainted(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        txtEnterCity.setForeground(new java.awt.Color(0, 102, 102));
        add(txtEnterCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 30));

        addCityjLabel.setBackground(new java.awt.Color(255, 255, 255));
        addCityjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addCityjLabel.setForeground(new java.awt.Color(0, 102, 102));
        addCityjLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addCityjLabel.setText("Add City:");
        add(addCityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, 30));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Songti TC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Add Network");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 300, 46));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String name = txtEnterCity.getText();
        if (name.isEmpty()==true)
         {
          JOptionPane.showMessageDialog(null, "Please add a City ","Success", JOptionPane.INFORMATION_MESSAGE);
         }
         else
         {
            Network network = ecosystem.createAndAddNetwork();
            network.setNetworkName(name);
            populateLocationTable();
         }
        txtEnterCity.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        showPanel.remove(this);
        Component[] componentArray = showPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminWorkAreaJPanel sysAdminwjp = (SysAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LocationJTable;
    private javax.swing.JLabel addCityjLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEnterCity;
    // End of variables declaration//GEN-END:variables
}
