package HealthBuddy.ui.SysAdminWorkArea;


import java.awt.CardLayout;
import javax.swing.JPanel;
import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.UserData.*;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Nidhi Singh
 */
public class PatientViewJpanel extends javax.swing.JPanel 
{
    private JPanel showPanel;
    private EcoSystem system;
    private PatientData patient;
    /**
     * Creates new form CreatePatientAccount
     */
    public PatientViewJpanel(JPanel showPanel, PatientData patient) 
    {
        initComponents();
        this.system=system;
        this.showPanel=showPanel;
        this.patient = patient;
        txtPatientAddress.setEnabled(false);
        txtPatientCity.setEnabled(false);
        txtPatientName.setEnabled(false);
        txtPatientContactNumber.setEnabled(false);
        txtPatientState.setEnabled(false);
        txtZipCode.setEnabled(false);
        txtPatientUserName.setEnabled(false);
        txtPatientAddress.setText(patient.getAddress());
        txtPatientCity.setText(patient.getCity());
        txtPatientName.setText(patient.getPatientName());
        txtZipCode.setText(String.valueOf(patient.getZipCode()));
        txtPatientContactNumber.setText(patient.getContactNo());
        txtPatientState.setText(patient.getState());
        txtPatientUserName.setText(patient.getUsername());
        setSize(1540,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientContactNumber = new javax.swing.JTextField();
        txtPatientAddress = new javax.swing.JTextField();
        txtPatientCity = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtPatientState = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        txtPatientUserName = new javax.swing.JTextField();
        lblUserPhoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Information"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 102));
        lblName.setText("Patient's Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, -1, -1));

        lblPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(0, 102, 102));
        lblPhoneNumber.setText("Phone Number");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 136, -1, -1));

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 102, 102));
        lblAddress.setText("Address Line1");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, -1, -1));

        lblCity.setBackground(new java.awt.Color(255, 255, 255));
        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 102, 102));
        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 212, -1, -1));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setText("View Patient Account");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 300, 35));

        lblState.setBackground(new java.awt.Color(255, 255, 255));
        lblState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(0, 102, 102));
        lblState.setText("State");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 250, -1, -1));

        lblZipCode.setBackground(new java.awt.Color(255, 255, 255));
        lblZipCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblZipCode.setForeground(new java.awt.Color(0, 102, 102));
        lblZipCode.setText("ZipCode");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, -1, -1));

        txtPatientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatientName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 87, 181, -1));

        txtPatientContactNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatientContactNumber.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPatientContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 131, 181, -1));

        txtPatientAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatientAddress.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 169, 181, -1));

        txtPatientCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatientCity.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPatientCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 207, 181, -1));

        txtZipCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 283, 181, -1));

        txtPatientState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatientState.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPatientState, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 245, 181, -1));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1315, 30, 90, 40));

        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 102, 102));
        lblUserName.setText("UserName");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 326, -1, -1));

        txtPatientUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPatientUserName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPatientUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 321, 181, -1));
        add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 87, 60, 120));

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/patientinfo.gif")).getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 660, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        showPanel.remove(this);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel); 
    }//GEN-LAST:event_btnBackActionPerformed
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientCity;
    private javax.swing.JTextField txtPatientContactNumber;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientState;
    private javax.swing.JTextField txtPatientUserName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
