package HealthBuddy.ui.SysAdminWorkArea;


import java.awt.CardLayout;
import javax.swing.JPanel;
import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.UserData.*;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Nidhi Singh
 */
public class PatientViewJpanel extends javax.swing.JPanel 
{
    private JPanel showPanel;
    private EcoSystem system;
    private PatientData patient;
    /**
     * Creates new form CreatePatientAccount
     */
    public PatientViewJpanel(JPanel showPanel, PatientData patient) 
    {
        initComponents();
        this.system=system;
        this.showPanel=showPanel;
        this.patient = patient;
        addtext.setEnabled(false);
        citytxt.setEnabled(false);
        nameText.setEnabled(false);
        mobileText.setEnabled(false);
        statetxt.setEnabled(false);
        zipcodeText.setEnabled(false);
        unameText.setEnabled(false);
        addtext.setText(patient.getAddress());
        citytxt.setText(patient.getCity());
        nameText.setText(patient.getPatientName());
        zipcodeText.setText(String.valueOf(patient.getZipCode()));
        mobileText.setText(patient.getContactNo());
        statetxt.setText(patient.getState());
        unameText.setText(patient.getUsername());
        setSize(1540,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        mobileNumberLabel = new javax.swing.JLabel();
        addlable = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        statelable = new javax.swing.JLabel();
        codelable = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        addtext = new javax.swing.JTextField();
        citytxt = new javax.swing.JTextField();
        zipcodeText = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        unameLabel = new javax.swing.JLabel();
        unameText = new javax.swing.JTextField();
        lblUserPhoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Information"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 102));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Patient's Name:");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, -1));

        mobileNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        mobileNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobileNumberLabel.setForeground(new java.awt.Color(0, 102, 102));
        mobileNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mobileNumberLabel.setText("Mobile Number:");
        add(mobileNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 170, -1));

        addlable.setBackground(new java.awt.Color(255, 255, 255));
        addlable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addlable.setForeground(new java.awt.Color(0, 102, 102));
        addlable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addlable.setText("Address Line1:");
        add(addlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 170, -1));

        citylabel.setBackground(new java.awt.Color(255, 255, 255));
        citylabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        citylabel.setForeground(new java.awt.Color(0, 102, 102));
        citylabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        citylabel.setText("City:");
        add(citylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 170, -1));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setText("Patient Details");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 300, 35));

        statelable.setBackground(new java.awt.Color(255, 255, 255));
        statelable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statelable.setForeground(new java.awt.Color(0, 102, 102));
        statelable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        statelable.setText("State:");
        add(statelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 170, -1));

        codelable.setBackground(new java.awt.Color(255, 255, 255));
        codelable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codelable.setForeground(new java.awt.Color(0, 102, 102));
        codelable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        codelable.setText("Postal Code:");
        add(codelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 170, -1));

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 102, 102));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 181, -1));

        mobileText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobileText.setForeground(new java.awt.Color(0, 102, 102));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 181, -1));

        addtext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addtext.setForeground(new java.awt.Color(0, 102, 102));
        add(addtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 181, -1));

        citytxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        citytxt.setForeground(new java.awt.Color(0, 102, 102));
        add(citytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 181, -1));

        zipcodeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zipcodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextActionPerformed(evt);
            }
        });
        add(zipcodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 181, -1));

        statetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statetxt.setForeground(new java.awt.Color(0, 102, 102));
        add(statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 181, -1));

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1315, 30, 90, 40));

        unameLabel.setBackground(new java.awt.Color(255, 255, 255));
        unameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unameLabel.setForeground(new java.awt.Color(0, 102, 102));
        unameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        unameLabel.setText("Username:");
        add(unameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 170, -1));

        unameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unameText.setForeground(new java.awt.Color(0, 102, 102));
        add(unameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 181, -1));
        add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 87, 60, 120));

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/patientinfo.gif")).getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 660, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        showPanel.remove(this);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel); 
    }//GEN-LAST:event_backButtonActionPerformed

    private void zipcodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextActionPerformed
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addlable;
    private javax.swing.JTextField addtext;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel citylabel;
    private javax.swing.JTextField citytxt;
    private javax.swing.JLabel codelable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel mobileNumberLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel statelable;
    private javax.swing.JTextField statetxt;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel unameLabel;
    private javax.swing.JTextField unameText;
    private javax.swing.JTextField zipcodeText;
    // End of variables declaration//GEN-END:variables
}
