package HealthBuddy.ui.TrustVolunteer;

import javax.swing.JPanel;
import javax.swing.JOptionPane;
import HealthBuddy.models.EcoSystem;
import javax.swing.table.DefaultTableModel;
import HealthBuddy.models.Trust.Donation.TrustDetails;
import HealthBuddy.models.Enterprise.EnterpriseTrust;
import HealthBuddy.models.Network.Network;
import HealthBuddy.models.Trust.Organisation.TrustOrgVolunteer;
import HealthBuddy.models.WorkQueue.HealthcareTrustRequestWQ;
import HealthBuddy.models.User.User;
import HealthBuddy.Config.SendEmailUtility;
import HealthBuddy.models.WorkQueue.WorkRequest;
import HealthBuddy.Config.Config;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Bhawna Singh
 */
public class WorkAreaVolunteerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaVolunteerJPanel
     */
    private JPanel displayJPanel;
    private EcoSystem ecosystem;
    private EnterpriseTrust enterprise;
    private Network network;
    private User userAccount;
 
    public WorkAreaVolunteerJPanel(JPanel displayJPanel,User account, TrustOrgVolunteer orgVolunteer ,EnterpriseTrust enterprise, Network network, EcoSystem ecosystem) {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.network = network;
        this.ecosystem = ecosystem;
        setSize(1540,800);
        
        //Setting label values
        lblVolunteerName9.setText(userAccount.getUsername());
        lblFundsOrgName9.setText(this.enterprise.getName());
        lblFundsOrgCity9.setText(network.getNetworkName());
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        tblPatientCharity9 = new javax.swing.JTable();
        lblWelcome9 = new javax.swing.JLabel();
        lblFundsName9 = new javax.swing.JLabel();
        lblFundsOrgName9 = new javax.swing.JLabel();
        lblFundsName19 = new javax.swing.JLabel();
        lblFundsOrgCity9 = new javax.swing.JLabel();
        btnPublish9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVolunteerName9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblPatientCharity9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPatientCharity9.setForeground(new java.awt.Color(0, 102, 102));
        tblPatientCharity9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PatientName", "Address", "Hospital", "Funds Required", "Newsletter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblPatientCharity9);

        lblWelcome9.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblWelcome9.setForeground(new java.awt.Color(0, 102, 102));
        lblWelcome9.setText(", Thank You For Your Valuable Contribution");

        lblFundsName9.setBackground(new java.awt.Color(255, 255, 255));
        lblFundsName9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFundsName9.setForeground(new java.awt.Color(0, 102, 102));
        lblFundsName9.setText("Funding Organisation Name:");

        lblFundsOrgName9.setBackground(new java.awt.Color(255, 255, 255));
        lblFundsOrgName9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFundsOrgName9.setForeground(new java.awt.Color(0, 102, 102));
        lblFundsOrgName9.setText("value");

        lblFundsName19.setBackground(new java.awt.Color(255, 255, 255));
        lblFundsName19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFundsName19.setForeground(new java.awt.Color(0, 102, 102));
        lblFundsName19.setText("Funding Organisation Address:");

        lblFundsOrgCity9.setBackground(new java.awt.Color(255, 255, 255));
        lblFundsOrgCity9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFundsOrgCity9.setForeground(new java.awt.Color(0, 102, 102));
        lblFundsOrgCity9.setText("value");

        btnPublish9.setBackground(new java.awt.Color(0, 102, 102));
        btnPublish9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPublish9.setForeground(new java.awt.Color(255, 255, 255));
        btnPublish9.setText("Publish Journal");
        btnPublish9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublish9ActionPerformed(evt);
            }
        });

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/volunteer.jpeg")).getImage().getScaledInstance(600, 600, Image.SCALE_DEFAULT));

        jLabel1.setIcon(imageIcon);

        lblVolunteerName9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblVolunteerName9.setForeground(new java.awt.Color(0, 102, 102));
        lblVolunteerName9.setText("value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFundsName19)
                                    .addComponent(lblFundsName9, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFundsOrgName9, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(lblFundsOrgCity9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(btnPublish9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVolunteerName9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblWelcome9, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome9)
                    .addComponent(lblVolunteerName9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFundsName9)
                            .addComponent(lblFundsOrgName9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFundsName19)
                            .addComponent(lblFundsOrgCity9))
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnPublish9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublish9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublish9ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPatientCharity9.getModel();
        int selectedRow = tblPatientCharity9.getSelectedRow();
        
        if (selectedRow > -1)
        {
            HealthcareTrustRequestWQ request = (HealthcareTrustRequestWQ)tblPatientCharity9.getValueAt(selectedRow,0);
            
            if(request.getStatus().equalsIgnoreCase("Published"))
            {
                JOptionPane.showMessageDialog(null, "Newsletter Publication Already made!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                request.setStatus("Published");
                populateTable();
                int count =0;
                for(TrustDetails funds : ecosystem.getDonationDirectory().getTrustCatalog())
                {
                    if(funds.geTrustOrgName().equalsIgnoreCase(enterprise.getName()))
                    {
                        count++;
                    }
                }
        
                String[] receiver = new String[count];
        
                int index =0;
                for(TrustDetails donation : ecosystem.getDonationDirectory().getTrustCatalog())
                {
                    if(donation.geTrustOrgName().equalsIgnoreCase(enterprise.getName()))
                    {
                        receiver[index++] = donation.getDonor().getEmail();
                    }
                }
        
                
                //Defining newsletter details

        
                String message = "Hi Donor," +",\n\nHope you are doing well! Your contribution brought a big change in saving lives!! Thank you for your help...!!!" + "\nBelow is the list of patients  whose life was saved because of you:\n" +"\n"+"Patient Name: "+request.getPatientName()+ "\nHospital Name: " + request.getHospitalName()+"\nHospital City: " + request.getCity() + "\nDonation Provided: "+request.getAmount()+"\n\nRegards,\n HealthBuddy Team";
                String subject ="News @ HealthBuddy";
                SendEmailUtility.sendEmail(subject, Config.emailId, Config.password, message, receiver);
        
                JOptionPane.showMessageDialog(null, "Publication of NewsLetter Successful!!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Kindly select a record you would like to Broadcast.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
            
    }//GEN-LAST:event_btnPublish9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblFundsName19;
    private javax.swing.JLabel lblFundsName9;
    private javax.swing.JLabel lblFundsOrgCity9;
    private javax.swing.JLabel lblFundsOrgName9;
    private javax.swing.JLabel lblVolunteerName9;
    private javax.swing.JLabel lblWelcome9;
    private javax.swing.JTable tblPatientCharity9;
    // End of variables declaration//GEN-END:variables

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblPatientCharity9.getModel();
        model.setRowCount(0);
        
        for(WorkRequest workRequest : network.getFundsRequests().getWorkRequestList())
        {
            HealthcareTrustRequestWQ fundsReqWorkQueue = (HealthcareTrustRequestWQ)workRequest;
                
            if(fundsReqWorkQueue.getMessage().equalsIgnoreCase("Acknowledged") && fundsReqWorkQueue.getFunderName().equalsIgnoreCase(enterprise.getName()))
            {
                Object[] row = new Object[5];
                row[0] = fundsReqWorkQueue;
                row[1] = fundsReqWorkQueue.getCity();
                row[2] = fundsReqWorkQueue.getHospitalName();
                row[3] = fundsReqWorkQueue.getAmount();
                row[4] = fundsReqWorkQueue.getStatus();
                
                model.addRow(row);
            }
        }          
    }
}
