package HealthBuddy.ui.TrustManager;

import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Enterprise.Enterprise;
import java.awt.Image;
import HealthBuddy.models.User.User;
import HealthBuddy.models.Trust.Donation.TrustDetails;
import javax.swing.ImageIcon;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Nidhi Singh
 */
public class AllDonationInformationJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private JPanel showPanel;
    private Enterprise enterprise;
    private User userAccount;

    /**
     * Creates new form ViewDonationJPanel
     */
    public AllDonationInformationJPanel(JPanel showPanel, EcoSystem ecoSystem, Enterprise enterprise, User userAccount) {
        initComponents();
        this.showPanel = showPanel;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.userAccount = userAccount;

        valueLable.setText(enterprise.getName());

        populateJTable();
        setSize(1540, 800);
    }

    public void populateJTable() {
        DefaultTableModel model = (DefaultTableModel) donationDetailsJTable.getModel();

        model.setRowCount(0);

        for (TrustDetails dd : ecoSystem.getDonationDirectory().getTrustCatalog()) {
            if (dd.geTrustOrgName().equalsIgnoreCase(valueLable.getText())) {
                Object[] row = new Object[3];
                row[0] = dd.getDonor().getDonorName();
                row[1] = dd.getDonation();
                row[2] = dd.getDonationDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationDetailsJTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        valueLable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Donations Details"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setText("Donation Information");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 450, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        donationDetailsJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donationDetailsJTable.setForeground(new java.awt.Color(0, 102, 102));
        donationDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Donor Name", "Donation Amount", "Donation Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donationDetailsJTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(donationDetailsJTable);
        if (donationDetailsJTable.getColumnModel().getColumnCount() > 0) {
            donationDetailsJTable.getColumnModel().getColumn(0).setResizable(false);
            donationDetailsJTable.getColumnModel().getColumn(1).setResizable(false);
            donationDetailsJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 677, 110));

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, 90, 30));

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 102));
        nameLabel.setText("Funding Organisation Name :");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 300, -1));

        valueLable.setBackground(new java.awt.Color(255, 255, 255));
        valueLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLable.setForeground(new java.awt.Color(0, 102, 102));
        valueLable.setText("value");
        add(valueLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 90, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 830, -1));

        ImageIcon imageIcon =  new ImageIcon(new ImageIcon(getClass().getResource("/HealthBuddy/ui/images/viewdonation.gif")).getImage().getScaledInstance(600, 500, Image.SCALE_DEFAULT));
        jLabel1.setIcon(imageIcon);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 650, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        showPanel.remove(this);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable donationDetailsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel valueLable;
    // End of variables declaration//GEN-END:variables
}
