package HealthBuddy.ui.TrustManager;

import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Enterprise.Enterprise;
import HealthBuddy.models.User.User;
import HealthBuddy.models.Trust.Donation.TrustDetails;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Nidhi Singh
 */
public class AllDonationInformationJPanel extends javax.swing.JPanel 
{
    private EcoSystem ecoSystem;
    private JPanel showPanel;
    private Enterprise enterprise;
    private User userAccount;
    /**
     * Creates new form ViewDonationJPanel
     */
    public AllDonationInformationJPanel(JPanel showPanel, EcoSystem ecoSystem, Enterprise enterprise, User userAccount)
    {
        initComponents();
        this.showPanel = showPanel;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        lblValue.setText(enterprise.getName());
        
        populateJTable();
        setSize(1540,800);
    }
    
    public void populateJTable()
    {
        DefaultTableModel model = (DefaultTableModel) donationDetailsJTable.getModel();
        
        model.setRowCount(0);
        
        for(TrustDetails dd : ecoSystem.getDonationDirectory().getTrustCatalog())
        {
            if(dd.geTrustOrgName().equalsIgnoreCase(lblValue.getText()))
            {
                Object[] row = new Object[3];
                row[0] = dd.getDonor().getDonorName();
                row[1] = dd.getDonation();
                row[2] = dd.getDonationDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationDetailsJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Donations Details"));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setText("Donation Information");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 450, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        donationDetailsJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donationDetailsJTable.setForeground(new java.awt.Color(0, 102, 102));
        donationDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Donor Name", "Donation Amount", "Donation Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donationDetailsJTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(donationDetailsJTable);
        if (donationDetailsJTable.getColumnModel().getColumnCount() > 0) {
            donationDetailsJTable.getColumnModel().getColumn(0).setResizable(false);
            donationDetailsJTable.getColumnModel().getColumn(1).setResizable(false);
            donationDetailsJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 677, 110));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, 90, 30));

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 102));
        lblName.setText("Funding Organisation Name :");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, -1));

        lblValue.setBackground(new java.awt.Color(255, 255, 255));
        lblValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblValue.setForeground(new java.awt.Color(0, 102, 102));
        lblValue.setText("value");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 90, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 830, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        showPanel.remove(this);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTable donationDetailsJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
