package HealthBuddy.ui.TrustManager;

import HealthBuddy.models.EcoSystem;
import HealthBuddy.models.Organisation.Organisation;
import HealthBuddy.models.Enterprise.EnterpriseTrust;
import HealthBuddy.models.Enterprise.Enterprise;
import HealthBuddy.models.Network.Network;
import HealthBuddy.models.WorkQueue.TrustReceiveWR;
import HealthBuddy.models.Healthcare.Organisation.HealthcareOrganisationAssistant;
import HealthBuddy.models.WorkQueue.HealthcareTrustRequestWQ;
import HealthBuddy.models.WorkQueue.WorkRequest;
import HealthBuddy.models.User.User;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Nidhi Singh
 */
public class PatientsCureSponsoringInformation extends javax.swing.JPanel 
{
    private JPanel showPanel;
    private FundingEnterprise fundingEnterprise;
    private Network network;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    String funds;
    Float amountFromFunding;
    /**
     * Creates new form ViewPatienttoSponsorJPanel
     */
    public PatientsCureSponsoringInformation(JPanel showPanel,EnterpriseTrust fundingEnterprise, Network network,EcoSystem ecoSystem, User userAccount, String funds ) 
    {
        initComponents();
        this.showPanel = showPanel;
        this.fundingEnterprise = fundingEnterprise;
        this.network = network;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.funds = funds;
        
        amountFromFunding = Float.parseFloat(funds);
        
        populateJTable();
    }
    
    public void populateJTable()
    {
            DefaultTableModel model = (DefaultTableModel) patientSponsorshipJTable.getModel();
        
            model.setRowCount(0);
            for(WorkRequest request : network.getFundsRequests().getWorkRequestList())
            {
                HealthcareTrustRequestWQ hospitalFundsRequestWorkQueue;
                hospitalFundsRequestWorkQueue = (HealthcareTrustRequestWQ)request;
                Object[] row = new Object[5];
                row[0] = hospitalFundsRequestWorkQueue;
                row[1] = hospitalFundsRequestWorkQueue.getAmount();
                row[2] = hospitalFundsRequestWorkQueue.getMessage();
                row[3] = hospitalFundsRequestWorkQueue.getHospitalName();
                row[4] = hospitalFundsRequestWorkQueue.getCity();
                model.addRow(row);
            }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientSponsorshipJTable = new javax.swing.JTable();
        btnSelectSponsor = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 219, 69));
        setBorder(javax.swing.BorderFactory.createTitledBorder("View Patients"));

        lblTitle.setFont(new java.awt.Font("Songti TC", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(59, 186, 210));
        lblTitle.setText("SPONSOR PATIENTS TREATMENT");

        patientSponsorshipJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Amount", "Message", "Hospital", "Hospital Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientSponsorshipJTable);
        if (patientSponsorshipJTable.getColumnModel().getColumnCount() > 0) {
            patientSponsorshipJTable.getColumnModel().getColumn(0).setResizable(false);
            patientSponsorshipJTable.getColumnModel().getColumn(1).setResizable(false);
            patientSponsorshipJTable.getColumnModel().getColumn(2).setResizable(false);
            patientSponsorshipJTable.getColumnModel().getColumn(3).setResizable(false);
            patientSponsorshipJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        btnSelectSponsor.setFont(new java.awt.Font("Songti TC", 1, 14)); // NOI18N
        btnSelectSponsor.setForeground(new java.awt.Color(0, 51, 102));
        btnSelectSponsor.setText("Sponsor");
        btnSelectSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSponsorActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Songti TC", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medistopUI.images/CharitibleGiving.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSelectSponsor)
                        .addGap(309, 309, 309)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle))
                    .addComponent(btnBack))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectSponsor))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSponsorActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) patientSponsorshipJTable.getModel();
        int selectedRow = patientSponsorshipJTable.getSelectedRow();
        if (selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Select a patient to sponsor", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            HealthcareTrustRequestWQ request = (HealthcareTrustRequestWQ)patientSponsorshipJTable.getValueAt(selectedRow,0);
            float amount = request.getAmount();
            
            if(amount<amountFromFunding)
            {
                if(request.getMessage().equals("Acknowledged"))
                {
                    JOptionPane.showMessageDialog(null,"Request Already Processed please select a different patient","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    request.setMessage("Acknowledged");
                    request.setReceiver(userAccount);
                    request.setFunderName(fundingEnterprise.getName());
                    populateJTable();
                    amountFromFunding = amountFromFunding-amount;
                    TrustReceiveWR recivedFundWorkRequest = new TrustReceiveWR();
                    
                    recivedFundWorkRequest.setPatientName(request.getPatientName());
                    recivedFundWorkRequest.setFunderName(fundingEnterprise.getName());
                    recivedFundWorkRequest.setCity(network.getNetworkName());
                    recivedFundWorkRequest.setDateReceived(new Date());
                    recivedFundWorkRequest.setHospitalName(request.getHospitalName());
                    recivedFundWorkRequest.setSender(userAccount);
                    recivedFundWorkRequest.setFundsSponsored(String.valueOf(request.getAmount()));
                    
                    Enterprise enterprise = null;
                    for(Network net: ecoSystem.getNetworkList())
                    {
                        for(Enterprise enter : net.getEnterpriseCatalog().getEnterpriseList())
                        {
                            if(enter.getName().equalsIgnoreCase(request.getHospitalName()))
                            {
                                enterprise = enter;
                                break;
                            }
                        }
                    }
            
                    HealthcareOrganisationAssistant org = null;
                    for (Organisation organi : enterprise.getOrganizationCatalog().getOrganizationList())
                    {
                        if(organi instanceof HealthcareOrganisationAssistant)
                        {
                            for(User uacc : organi.getUserCatalog().getUserCatalog())
                            {
                                if(uacc.getUsername().equalsIgnoreCase(request.getSender().getUsername()))
                                {
                                    org = (HealthcareOrganisationAssistant)organi;
                                    break;
                                }
                            }
                        }
                    }
                    org.getFundsReceived().getWorkRequestList().add(recivedFundWorkRequest);
                    userAccount.getWorkQueue().getWorkRequestList().add(recivedFundWorkRequest);
                
                    JOptionPane.showMessageDialog(null, "Hospital Request successfully acknowledged by hospital", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Funding Oranisation can't sponsor the treatment due to money sortage", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSelectSponsorActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        showPanel.remove(this);
        CardLayout layout = (CardLayout) showPanel.getLayout();
        layout.previous(showPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectSponsor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable patientSponsorshipJTable;
    // End of variables declaration//GEN-END:variables
}
